### PR TITLE
Add MacOS support

### PR DESCRIPTION
**Pull request by tauraamui**
This PR enables the engine to be built and run on macOS intel/apple silicon. I'm unsure if these changes will still allow the Linux make build directive to work despite the compiler not knowing what `-framework` means presumably. This is the first time I've really worked on a C project in a very very long time so bear with me.

The highest supported version of OpenGL on macOS (and seemingly permenantly) is 4.1. Your engine nor your shaders appear to be using 4.6 exclusive features, so if you're interested in easily supporting Windows macOS + Linux then I guess you should keep the version to this for OpenGL for now?

(edit): huh, I just watched a bit more of your source code walkthrough video, the shader result does look way different.) so maybe you really do need versions higher than 4.1. Shit.

ScreenRecording2024-11-29at10 28 32-ezgif com-video-to-gif-converter

(edit - again):

Never mind there's basically nothing in the shader, I've set it to wireframe mode for the gizmo cubes and it looks exactly right now.

### CODE REVIEW

**Comment by beholdenspore28** [comment]
Yea that looks right to me. It was definitely the wireframe bool.

**Comment by tauraamui** [comment]
> Yea that looks right to me. It was definitely the wireframe bool.

I just realised I removed the -lGL flag which does break the build on macOS. So I suppose we'd need to add a new Make phoney for building on macos.

**Comment by beholdenspore28** [comment]
yea this would break linux support in its current state. You should add a separate variable LIB_MACOS, CFLAGS_MACOS, etc..

**Comment by tauraamui** [comment]
Okidoki!

**Comment by tauraamui** [comment]
@beholdenspore28 done that, let me know what you think!

**Comment by tauraamui** [comment]
Is this PR ok to merge?

**Comment by beholdenspore28** [comment]
Yessir! Thank you for your effort! :D I'll merge this right away. I was giving you some time to cook, came back this morning and saw your changes. Looks good!

**Comment by beholdenspore28** [comment]
OOPS i accidentally closed instead of merging lol

**Pull request merged**
